name: Kingdoms
main: com.kingdomscrusade.Kingdoms.KingdomsMain
version: 0.1.1-alpha
author: "Little Hill MYR"
api-version: 1.16
commands:
  kingdoms:
    description: Give a list of active Kingdoms.
    usage: /<command> <args1>