name: ${project.name}
main: net.kingdomscrusade.Kingdoms.KingdomsMain
version: ${project.version}
author: Little Hill MYR
description: ${project.description}
website: ${project.url}
api-version: 1.16
commands:
  kc:
    description: Command to access KCDIGP plugin!
    usage: /<command> ? for more info.