name: Kingdoms
main: com.kingdomscrusade.Kingdoms.KingdomsMain
version: v0.2-alpha
author: "Little Hill MYR"
api-version: 1.16
depend:
  - NickNamer
softdepend:
  - NickNamer
commands:
  kingdoms:
    description: Give a list of active Kingdoms.
    usage: /<command> <args1>